collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /tag/:name/

title: thsieh4
url: "https://thsieh4.github.io/"
baseurl: ""
github_username: thsieh4
permalink: pretty
